name: Push to GitHub Pages on other repo

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout Other Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PUSH_TOKEN }}
        repository: lgdesviante/lgdesviante.github.io
        ref: main
        path: './www'

    - name: Push other repo
      run: |
        cd www
        git push origin :gh-pages &>/dev/null || true
        git switch --orphan gh-pages
        cp -r ../*.html ../*.gif ../*.ico ../*.css ../js ../imgs ../fontes ./
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "update gh-pages"
        git push origin gh-pages
